### ISSUE TITLE
Breakpoint failure

### ISSUE THREAD

**Issue by sxzxs** [Nihilus118/vscode-perl-debug#1]
if in this situation: Breakpoint failure

`**BEGIN{unshift @INC, './lib'}**;`
```
#!/usr/bin/perl

BEGIN{unshift @INC, './lib'};

use strict;
use warnings;
use Data::Dumper;

print "ok";
```

**Comment by Nihilus118** [comment]
Unfortunately this seems to be an issue with the Perl debugger itself.
When I manually start a debugging session it will start on line 9 without a chance for interruption:

`perl -d ./issue_1.pl
...
main::(.\issue_1.pl:9): print "ok";`

Setting a breakpoint on line 3 while already being on line 9 is in fact useless.
Even when I modify the code snippet I can not get the perl debugger to do what I want:

`  DB<1> l
3==>    print "test\n";
4
5:      BEGIN{unshift @INC, './lib'};
6
7:      use strict;
8:      use warnings;
9:      use Data::Dumper;
10
11:     print "ok";
  DB<1> b 5
  DB<2> c
A
okDebugged program terminated.  Use q to quit or R to restart,
use o inhibit_exit to avoid stopping after program termination,
h q, h R or h o to get additional info.`

I will investigate further and try to find a way around it.

**Comment by Nihilus118** [comment]
After consulting [reddit](https://www.reddit.com/r/perl/comments/13ptkgz/make_perl_debugger_stop_before_use_statements/) we found two solutions that seem to work. The simplest one seems to be this one:
```
#!/usr/bin/perl

BEGIN{
    $DB::single = 1;
    unshift @INC, './lib'
};

use strict;
use warnings;
use Data::Dumper;

print "ok";
```
Adding this line of code forces the Perl debugger to stop on line 5. As my debug adapter only invokes **perl -d** it recognizes the breakpoint without any other setup required.

**Comment by Nihilus118** [comment]
@sxzxs I hope the answers resolved your problem. I will close this issue for now because of inactivity.
If you encounter any other problems with the debugger feel free to open another issue.
Thank you for testing and helping to improve this project!
