### ISSUE TITLE
List this adapter

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [Nihilus118/vscode-perl-debug#5]
This adapter should be listed at https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/.

At the bottom of that document it says 
```
If you are missing a debug adapter implementation please create a pull request in GitHub against this markdown document
```
The markdown document is here: https://github.com/Microsoft/debug-adapter-protocol/blob/gh-pages/_implementors/adapters.md

Thank you!

**Comment by bmeneg** [comment]
Considering the Perl Debug project pointed out by the table is already archived, I went ahead and opened a PR to update it pointing to this project here:

https://github.com/microsoft/debug-adapter-protocol/pull/428

**Comment by Nihilus118** [comment]
@bmeneg thank you for creating the PR! As it is already merged I will close this issue.
